#!/bin/bash
START='++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
B2=b2
which b2 || B2=bjam
(echo $START; $B2 "$@" 2>&1) | colourise red $START red ' error' green 'Running build from'  yellow ' warning'
