#!/bin/bash -e

TWICPGN=twic.pgn.gz
DEDUPED=twic-deduped.pgn.gz
#DOWNLOAD_URL=http://www.chesscenter.com/twic/zips
DOWNLOAD_URL=http://www.theweekinchess.com/zips

#
# For each week get the PGN, remove Ctrl-Ms, lines composing of '-' and compress
#
week=211
while true
do
    #
    # Get the zip file
    #
    zip_file=twic${week}g.zip
    [ -f $zip_file ] \
        || wget $DOWNLOAD_URL/$zip_file \
        || break
    #
    # Extract the contents
    #
    unzip -p $zip_file
    #
    # Increase the week counter
    #
    week=$(($week + 1))
done | sed 's///g' | tidy-twic-pgn | gzip -c > $TWICPGN



#
# Dedupe and make into a SCID database
#
echo "Deduplicating..."
zcat $TWICPGN | pgn-extract -s -D | gzip -c >$DEDUPED
#rm $TWICPGN
echo "Converting to SCID format"
pgnscid -f $DEDUPED TWIC
#rm $DEDUPED
