#!/usr/bin/env python3

from bs4 import BeautifulSoup
import urllib2
from optparse import OptionParser

top_level_url = 'https://webcast.chessclub.com/'
url = 'https://webcast.chessclub.com/icc/i/GOTW/2013_08_02/Benjamin_GOTW.html'
old_url = 'https://webcast.chessclub.com/icc/i/Biel12/Round4/GOTD.html'

# Set up options
parser = OptionParser()
parser.add_option(
    "-u", "--user",
    help="Use USER as username for HTTP authorization", metavar="USER")
parser.add_option(
    "-p", "--password",
    help="Use PASS as password for HTTP authorization", metavar="PASS")
options, args = parser.parse_args()

# create a password manager
password_mgr = urllib2.HTTPPasswordMgrWithDefaultRealm()

# Add the username and password.
# If we knew the realm, we could use it instead of None.
password_mgr.add_password(None, top_level_url, options.user, options.password)

# create "opener" (OpenerDirector instance)
handler = urllib2.HTTPBasicAuthHandler(password_mgr)
opener = urllib2.build_opener(handler)
firefox_user_agent = 'Mozilla/5.0 (X11; U; Linux i686) ' \
    'Gecko/20071127 Firefox/2.0.0.11'
opener.addheaders = [('User-agent', firefox_user_agent)]

# Install the opener.
# Now all calls to urllib2.urlopen use our opener.
urllib2.install_opener(opener)

soup = BeautifulSoup(urllib2.urlopen(url))
