#!/usr/bin/env python3

"""
Script to identify files in the current directory that look like photos
named by year and month. The script organises the identified photos into
folders named by year and month.
"""

import os
import re
import shutil

EXAMPLE_FILE = '20170821_184315_004_01.jpg'
PHOTO_RE = '(\d{4})(\d{2})\d{2}_\d{6}'

photo_pattern = re.compile(PHOTO_RE)

for filename in os.listdir('.'):
  match = photo_pattern.match(filename)
  if match is None:
    print('DID NOT MATCH: {}'.format(filename))
  else:
    # print('{}: {}'.format(match.groups(), filename))
    year, month = match.groups()
    dirname = os.path.join(year, '{}-{}'.format(year, month))
    os.makedirs(dirname, exist_ok=True)
    shutil.move(filename, os.path.join(dirname, filename))
