#!/usr/bin/env python
"""
Test if pytorch is using the GPU.
"""

import torch
import time

print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
time.sleep(5)
