#!/usr/bin/env python

import tempfile
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

print(f'Backend is {mpl.rcParams["backend"]}')
print(f'Matplotlib is{"" if mpl.is_interactive() else " not"} interactive')

nsamples = 40
x = np.linspace(-1, 1, nsamples)
y = np.random.random(nsamples)
y.sort()
fig, ax = plt.subplots(figsize=(18, 12))
ax.plot(x, y)
fig.show()
with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as fp:
    print(f'Saving figure to {fp.name}')
    fig.savefig(fp)
