#!/usr/bin/env python3
"""
Test if pytorch is using the GPU.
"""

import torch
import time

print(f'Torch version: {torch.__version__}')
print(f'Current device: {torch.cuda.current_device()}')
print(f'Device count: {torch.cuda.device_count()}')
print(f'Device 0: {torch.cuda.device(0)}')
print(f'Device 0 name: {torch.cuda.get_device_name(0)}')
print(f'Cuda is available: {torch.cuda.is_available()}')
time.sleep(5)
